version: '3'

services:

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "5432:5432"

  frontend:
    build:
      context: ../../gui
      args:
        - NG_QS_AUTH_PLAYER_AUDIENCE=${NG_QS_AUTH_PLAYER_AUDIENCE}
        - NG_QS_AUTH_PLAYER_CLIENT_ID=${NG_QS_AUTH_PLAYER_CLIENT_ID}
        - NG_QS_AUTH_PLAYER_DOMAIN=${NG_QS_AUTH_PLAYER_DOMAIN}
        - NG_QS_AUTH_PLAYER_REDIRECT_URI=${NG_QS_AUTH_PLAYER_REDIRECT_URI}
    restart: always
    links:
      - platform-engine

  platform-engine:
    build: ../../platform-engine
    restart: always
    env_file:
      - variables.env
    links:
      - postgres
      - rabbitmq
      - redis

  score-engine:
    build: ../../score-engine
    restart: always
    env_file:
      - variables.env
    links:
      - platform-engine
      - rabbitmq
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro

  postgres:
    image: postgres:9.6
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file:
      - variables.env

  rabbitmq:
    image: rabbitmq:3.7
    env_file:
      - variables.env

  redis:
    image: redis
